### ISSUE TITLE
Create ListAnswer View 

### ISSUE THREAD

**Issue by TheRealSibasishBehera** [opencodeiiita/Forum-Backend#16]
use serialiser as `AnswerSerializer` , its not created yet so , add and comment that part

**Comment by TheRealSibasishBehera** [comment]
This issue is open to be claimed

**Comment by GammaMicrowave** [comment]
claim

**Comment by GammaMicrowave** [comment]
can you unassign me from this task

**Comment by frikinomad** [comment]
claim
