### ISSUE TITLE
Create a view to post question

### ISSUE THREAD

**Issue by TheRealSibasishBehera** [opencodeiiita/Forum-Backend#22]
use model :Question
serializer: QuestionSerializer

please add success and bad request error codes

**Comment by mugdha273** [comment]
claim

**Comment by frikinomad** [comment]
Claim

**Comment by frikinomad** [comment]
2 issues are assigned to same person from 1 repo

**Comment by frikinomad** [comment]
Please correct this

**Comment by frikinomad** [comment]
Assign this to me

**Comment by mugdha273** [comment]
> 2 issues are assigned to same person from 1 repo

added the PR for the earlier one, it was simply merging files 😅

**Comment by frikinomad** [comment]
Still against the rules

**Comment by TheRealSibasishBehera** [comment]
My bad guys 
I was not aware of that rule 
it says you cant work on multiple issue in same repo at one time 
I am assigning it @frikinomad
