### ISSUE TITLE
Create Question Model

### ISSUE THREAD

**Issue by TheRealSibasishBehera** [opencodeiiita/Forum-Backend#3]
`Question` would be the model where queries from users would be stored . Design it using django's native orm using the `models` module

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by akshatsgh** [comment]
claim

**Comment by TheRealSibasishBehera** [comment]
Great ! @akshatsgh , i have assigned you

**Comment by TheRealSibasishBehera** [comment]
This issue is open to be claimed

**Comment by vedant-z** [comment]
claim
