### ISSUE TITLE
Create url pattern for question_detail view ie put , patch , delete , update

### ISSUE THREAD

**Issue by TheRealSibasishBehera** [opencodeiiita/Forum-Backend#35]

**Comment by mugdha273** [comment]
Hey it's modelviewset, we don't need to add additional URL patterns in urls.py. They will work already just by providing <pk> in the end. Did I understand something wrong based on issue title?

**Comment by frikinomad** [comment]
is it up for claims or what ?

**Comment by TheRealSibasishBehera** [comment]
i think question view_set route is not yet used in the urls only answer_viewset is present as router
am i wrong? is there any work around for question viewset 
i am new to model viewset so it would be helpful

**Comment by TheRealSibasishBehera** [comment]
> is it up for claims or what ?
please wait , i will inform in a bit
i am closing it for now

**Comment by TheRealSibasishBehera** [comment]
feel free to comment here on question_viewset router , i think you can do that in a closed issue

**Comment by TheRealSibasishBehera** [comment]
makes sense 👍 . PR is merged
